# Generated by Django 5.1.6 on 2025-02-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('email', models.CharField(unique=True)),
                ('consumer_type', models.CharField(choices=[('Consumer', 'Consumer'), ('Rteailer', 'Retailer'), ('Food Processor', 'Food Processor'), ('Other', 'Other')], default='Consumer', max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('warehouse_location', models.TextField(blank=True, null=True)),
                ('bank_account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('upi_id', models.CharField(blank=True, max_length=50, null=True)),
                ('crops_intrested_in', models.TextField()),
                ('prefered_buying_method', models.CharField(choices=[('Direct From Farmer', 'Direct From Farmer'), ('Direct From Company', 'Direct From Company')], default='Direct From Farmer', max_length=20)),
                ('average_buying_quantity', models.PositiveIntegerField()),
                ('gst_certificate', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('business_license', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
