# Generated by Django 5.1.6 on 2025-02-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_consumer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='created_at',
        ),
        migrations.AddField(
            model_name='farmer',
            name='aadhaar_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/aadhaar/'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='aadhaar_number',
            field=models.CharField(default='000000000000', max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='ai_chatbot_assistance',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='farmer',
            name='bank_account_number',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='farmer',
            name='bank_passbook',
            field=models.FileField(blank=True, null=True, upload_to='documents/bank/'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='district',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='farmer',
            name='expected_harvest_season',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='farmer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='farmer',
            name='ifsc_code',
            field=models.CharField(default='00000000000', max_length=11),
        ),
        migrations.AddField(
            model_name='farmer',
            name='land_area',
            field=models.FloatField(default=0.0, help_text='Land area in acres or hectares'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='land_ownership',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Tenant', 'Tenant')], default='Owner', max_length=10),
        ),
        migrations.AddField(
            model_name='farmer',
            name='land_ownership_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/land/'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='main_crops_grown',
            field=models.TextField(default='None', help_text='Comma-separated crop names'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='mobile_number',
            field=models.CharField(default='0000000000', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='pincode',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='farmer',
            name='preferred_language',
            field=models.CharField(choices=[('Telugu', 'Telugu'), ('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=10),
        ),
        migrations.AddField(
            model_name='farmer',
            name='selling_option',
            field=models.CharField(choices=[('Direct Sale To Consumer/Retailer/Food_Processor', 'Direct Sale To Consumer//Retailer/Food_Processor'), ('Direct Sale To farmRule', 'Direct Sale To farmRule')], default='Direct Sale', max_length=50),
        ),
        migrations.AddField(
            model_name='farmer',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='farmer',
            name='terms_and_conditions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmer',
            name='upi_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='village_town',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='farmer',
            name='weather_market_alerts',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
