# Generated by Django 5.1.6 on 2025-02-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_remove_farmer_created_at_farmer_aadhaar_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to='documents/consumer/'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='gst_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/consumer/'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/consumer/'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='aadhaar_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/farmer/aadhaar/'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='bank_passbook',
            field=models.FileField(blank=True, null=True, upload_to='documents/farmer/bank/'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='land_ownership_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/farmer/land/'),
        ),
    ]
