# Generated by Django 5.1.6 on 2025-02-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_alter_consumer_business_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='full_name',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
