# Generated by Django 5.1.6 on 2025-02-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_alter_farmer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='aadhaar_number',
            field=models.CharField(default=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='mobile_number',
            field=models.CharField(default=True, max_length=20, unique=True),
        ),
    ]
