# Generated by Django 5.1.6 on 2025-02-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0008_alter_farmer_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='email',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
